# Generated by Django 6.0.3 on 2026-05-05 20:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneDeCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes spéciales')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('a_emporter', 'À emporter'), ('livraison', 'Livraison'), ('sur_place_generique', 'Sur place')], default='sur_place_generique', max_length=20, verbose_name='Type de commande')),
                ('nom_clt', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('adresse_liv', models.TextField(blank=True, null=True, verbose_name='Adresse de livraison')),
                ('date_creation_h', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_maj_h', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('preparee', 'Préparée'), ('servie', 'Servie'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_geres', to=settings.AUTH_USER_MODEL, verbose_name='Employé responsable')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_creation_h'],
            },
        ),
    ]
