# Generated by Django 6.0.3 on 2026-05-05 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('core', '0001_initial'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='core.table', verbose_name='Table assignée'),
        ),
        migrations.AddField(
            model_name='lignedecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande', verbose_name='Commande'),
        ),
        migrations.AddField(
            model_name='lignedecommande',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_commande', to='menus.plat', verbose_name='Plat'),
        ),
        migrations.AlterUniqueTogether(
            name='lignedecommande',
            unique_together={('commande', 'plat')},
        ),
    ]
