# Generated by Django 4.2.7 on 2026-05-23 10:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_configuration_table_emplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='serveur',
            field=models.ForeignKey(blank=True, help_text='Serveur responsable de cette table. Vide = tous les serveurs peuvent y accéder.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Serveur assigné'),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='salaire_mensuel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Salaire mensuel'),
        ),
        migrations.AlterField(
            model_name='caissier',
            name='salaire_mensuel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Salaire mensuel'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='salaire_mensuel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Salaire mensuel'),
        ),
        migrations.AlterField(
            model_name='serveur',
            name='salaire_mensuel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Salaire mensuel'),
        ),
    ]
